### ISSUE TITLE
update schimpy.station.py for flux.out format

### ISSUE THREAD

**Issue by lily-tomkovic-DWR** [CADWRDeltaModeling/schimpy#24]
* schimpy version: 1.3.4+30.gc1ed8e8
* Python version: 3.7.13
* Operating System: Windows 10

### Description

In running the station.py command read_flux_out() with outputs found in the Hello SCHISM tutorial, the following error arises:
_File "C:\Users\%userprofile%\Miniconda3\envs\schimpy\lib\site-packages\schimpy\station.py", line 304, in flux_stations_from_yaml
  if not "linestrings" in content: raise ValueError("Could not fine 'linestrings' key. Was the input a string or filename? Valid file?")_

I think this might be an issue of updated formatting for flux.out in SCHISM 5.10?

### What I Did

station_fpath = '../flow_station_xsects.yaml'
time_basis = datetime.datetime(2009, 2, 10)
set_color_cycle_dark2()

outputs_fpath = "../outputs/flux.out"
station_name = "montezuma_mouth"

all_ts = read_flux_out(outputs_fpath, station_fpath, time_basis)

**Traceback (most recent call last):**
  File "C:\Users\%userprofile%\Miniconda3\envs\schimpy\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\%userprofile%\Miniconda3\envs\schimpy\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\%userprofile%\.vscode\extensions\ms-python.python-2022.12.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\%userprofile%\.vscode\extensions\ms-python.python-2022.12.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\%userprofile%\.vscode\extensions\ms-python.python-2022.12.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\%userprofile%\.vscode\extensions\ms-python.python-2022.12.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\Users\%userprofile%\.vscode\extensions\ms-python.python-2022.12.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\Users\%userprofile%\.vscode\extensions\ms-python.python-2022.12.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "d:\SCHISM\Hello_SCHISM_Tutorial\tutorial_workshop_5.10\t1_output\exercises\exercise2.py", line 15, in <module>
    all_ts = read_flux_out(outputs_fpath, station_fpath, time_basis)
  File "C:\Users\%userprofile%\Miniconda3\envs\schimpy\lib\site-packages\schimpy\station.py", line 327, in read_flux_out
    names = station_names_from_file(names)
  File "C:\Users\%userprofile%\Miniconda3\envs\schimpy\lib\site-packages\schimpy\station.py", line 319, in station_names_from_file
    station_names = flux_stations_from_yaml(fpath)
  File "C:\Users\%userprofile%\Miniconda3\envs\schimpy\lib\site-packages\schimpy\station.py", line 304, in flux_stations_from_yaml
    if not "linestrings" in content: raise ValueError("Could not fine 'linestrings' key. Was the input a string or filename? Valid file?")
ValueError: Could not fine 'linestrings' key. Was the input a string or filename? Valid file?

**Comment by water-e** [comment]
What does the top of the file look like? Should look like this (format, not the particular station):

```
linestrings:
- agency_id: B95541
  coordinates:
  - - 642050.
    - 4188627.
  - - 642065.
    - 4188614.
  name: MRU
  station_id: MRU
  station_name: Middle River at Undine Road
```
