### ISSUE TITLE
osgeo.osr import fails

### ISSUE THREAD

**Issue by water-e** [CADWRDeltaModeling/schimpy#25]
* schimpy version: 1.3
* Python version: 3.7.13
* Operating System: windows

See below error? Are the imports outdated?

### What I Did
My issues originate here.

```
File "d:\delta\models\schimpy\schimpy\schism_polygon.py", line 8, in <module>
    from osgeo.osr import SpatialReference
```
But the context is general. Is this something that needs adjustment in our code? environments?

```
>>> import osgeo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\eli\miniconda3\envs\schimpy_env\lib\site-packages\osgeo\__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\eli\miniconda3\envs\schimpy_env\lib\site-packages\osgeo\__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "C:\Users\eli\miniconda3\envs\schimpy_env\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\eli\miniconda3\envs\schimpy_env\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
>>> import osgeo.osr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\eli\miniconda3\envs\schimpy_env\lib\site-packages\osgeo\__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\eli\miniconda3\envs\schimpy_env\lib\site-packages\osgeo\__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "C:\Users\eli\miniconda3\envs\schimpy_env\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\eli\miniconda3\envs\schimpy_env\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.
>>> print schimpy.__version__
  File "<stdin>", line 1
    print schimpy.__version__
```

**Comment by kjnam** [comment]
I think this issue is too old now. Is this still relevant?

**Comment by water-e** [comment]
Agreed.
